(function() {
  'use strict';

  const App = window.__App = window.__App || {};

  App.state = {
    currentWorkspace: null,
    currentFilePath: null,
    currentFileName: null,
    currentFileContent: null,
    saveTimeout: null,
    isSaving: false,
    isLoading: false,
    contextMenuTarget: null,
    slashPanelVisible: false,
    slashSelectedIndex: 0,
    slashFilter: '',
    lastModifiedTime: null,
    fileWatcherInterval: null,
    assetsFolderPath: null,
    savedWorkspaceTree: null,
    isPreviewMode: false,
    isOutlineEnabled: false,
    isReadingMode: false,
    currentZoom: 100,
    currentFontSize: 16,
    currentView: 'edit',
    currentTheme: 'light',
    expandedFolders: new Set(),
    savedCursorRange: null,
    isExitingCodeBlock: false
  };

  App.dom = {
    sidebar: null,
    fileTree: null,
    emptyState: null,
    workspaceName: null,
    recentList: null,
    recentEmpty: null,
    btnAdd: null,
    dropdownMenu: null,
    editor: null,
    editorPlaceholder: null,
    editorWrapper: null,
    editorWelcome: null,
    currentFileNameEl: null,
    saveStatus: null,
    wordCount: null,
    lineInfo: null,
    fileHeaderHint: null,
    fileHeaderTitle: null,
    outlineList: null,
    contextMenu: null,
    formatToolbar: null,
    imageContextMenu: null,
    imageContextTarget: null,
    tableContextMenu: null,
    tableContextTarget: null,
    slashPanel: null,
    slashList: null,
    conflictOverlay: null,
    conflictMessage: null,
    tableDialogOverlay: null,
    imageProgress: null,
    previewContent: null,
    dialogOverlay: null,
    dialogTitle: null,
    dialogInput: null,
    dialogCancel: null,
    dialogConfirm: null,
    confirmOverlay: null,
    confirmTitle: null,
    confirmMessage: null,
    confirmCancel: null,
    confirmOk: null,
    aboutOverlay: null,
    aboutClose: null,
    toolbar: null,
    zoomLevel: null,
    fontSizeDisplay: null,
    readingProgress: null,
    btnZoomDecrease: null,
    btnZoomIncrease: null,
    btnReadingMode: null,
    btnOutline: null,
    btnSearch: null,
    btnFullscreen: null,
    btnRefresh: null,
    btnFontDecrease: null,
    btnFontIncrease: null,
    btnTheme: null,
    themeDropdown: null,
    btnToggleSidebar: null,
    viewSwitch: null,
    searchPanel: null,
    searchInput: null,
    searchResults: null,
    searchClose: null,
    searchClear: null,
    searchInfo: null,
    sidebarTabs: null,
    sidebarSearch: null,
    sidebarSearchInput: null,
    sidebarSearchClear: null,
    searchPanelProject: null,
    searchInputProject: null,
    searchCloseProject: null,
    searchResultsProject: null,
    searchInfoProject: null,
    searchClearProject: null,
    mdViewToggle: null,
    mdViewBtns: null,
    mdSourceEditor: null,
    mdSourceTextarea: null,
    mdSourceLineNumbers: null,
    currentMdView: 'preview'
  };

  App.slashCommands = [
    { id: 'text', title: '普通文本', description: '普通段落', icon: '¶', action: () => App.editor_insert_ops.insertPlainText() },
    { id: 'h1', title: '一级标题', description: '大标题', icon: 'H1', action: () => App.editor_insert_ops.insertHeading(1) },
    { id: 'h2', title: '二级标题', description: '中标题', icon: 'H2', action: () => App.editor_insert_ops.insertHeading(2) },
    { id: 'h3', title: '三级标题', description: '小标题', icon: 'H3', action: () => App.editor_insert_ops.insertHeading(3) },
    { id: 'bold', title: '加粗', description: '文字加粗', icon: 'B', action: () => App.editor_insert_ops.wrapSelection('strong') },
    { id: 'italic', title: '斜体', description: '文字斜体', icon: 'I', action: () => App.editor_insert_ops.wrapSelection('em') },
    { id: 'strikethrough', title: '删除线', description: '文字删除线', icon: 'S', action: () => App.editor_insert_ops.wrapSelection('s') },
    { id: 'code', title: '行内代码', description: '行内代码片段', icon: '</>', action: () => App.editor_insert_ops.wrapSelection('code') },
    { id: 'codeblock', title: '代码块', description: '多行代码', icon: '{ }', action: () => App.editor_code_block.insertCodeBlock() },
    { id: 'link', title: '链接', description: '超链接', icon: '🔗', action: () => App.editor_insert_ops.insertLink() },
    { id: 'image', title: '图片', description: '插入本地图片', icon: '🖼', action: () => App.editor_insert_ops.insertImage() },
    { id: 'table', title: '表格', description: '插入表格', icon: '⊞', action: () => App.editor_insert_special.showTableDialog() },
    { id: 'ul', title: '无序列表', description: '项目符号列表', icon: '•', action: () => App.editor_content.insertList('ul') },
    { id: 'ol', title: '有序列表', description: '数字编号列表', icon: '1.', action: () => App.editor_content.insertList('ol') },
    { id: 'todo', title: '待办清单', description: '可勾选的任务列表', icon: '☐', action: () => App.editor_content.insertTodoList() },
    { id: 'blockquote', title: '引用', description: '引用块', icon: '"', action: () => App.editor_content.insertBlockquote() },
    { id: 'hr', title: '分割线', description: '水平分隔线', icon: '—', action: () => App.editor_content.insertHorizontalRule() }
  ];

  App.icons = {
    folder: `<svg class="tree-item-icon" viewBox="0 0 18 18" fill="none">
      <path d="M2 4.5A1.5 1.5 0 0 1 3.5 3h3.172a1.5 1.5 0 0 1 1.06.44l.658.658H14.5A1.5 1.5 0 0 1 16 5.5v7a1.5 1.5 0 0 1-1.5 1.5h-11A1.5 1.5 0 0 1 2 12.5v-8z" stroke="currentColor" stroke-width="1.3"/>
    </svg>`,
    file: `<svg class="tree-item-icon" viewBox="0 0 18 18" fill="none">
      <path d="M10 1.5H5a1.5 1.5 0 0 0-1.5 1.5v12a1.5 1.5 0 0 0 1.5 1.5h8a1.5 1.5 0 0 0 1.5-1.5V6L10 1.5z" stroke="currentColor" stroke-width="1.3"/>
      <path d="M10 1.5v4.5h4.5" stroke="currentColor" stroke-width="1.3"/>
    </svg>`,
    arrow: `<svg class="tree-item-expand" viewBox="0 0 18 18" fill="none">
      <path d="M7 4l4 5-4 5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>`
  };

})();